### ISSUE TITLE
No module named 'mime.agent'

### ISSUE THREAD

**Issue by csufangyu** [rstrudel/rlbc#2]
Hi,thanks your job,It is very exciting！and when i try to run your code,when i run `python3 -m bc.collect_demos with configs/rlbc/section5/1.pick_collect_demos.json
`and I get a error,the eroor is:
`No module named 'mime.agent'`
and I find the code is:
`from mime.agent import ScriptAgent, ReplayAgent`
would you help me?thanks!

and I visited the home page,and found mime is the robotic environment for manipulation,could you open source it?

**Comment by rstrudel** [comment]
Hi, thanks for your interest in our work!
There is still work to do on mime before the open sourcing, it will probably take a month before we release it. Sorry about this setback, I will keep you posted when we release it.

**Comment by ZQ32** [comment]
I encountered the same problem

**Comment by SHYang1210** [comment]
I want to know if the environment about mime has been released.

**Comment by rstrudel** [comment]
This is ongoing work, the environments have not been released yet. We will post a link to it once released.

**Comment by freeliuzc** [comment]
Hi, your work  is very exciting！
But when will this problem be solved？

**Comment by rstrudel** [comment]
Hello,

It took a while but we released [mime](https://github.com/ikalevatykh/mime-release). You can now use it with our rlbc repository and train policies, please give it a try ! I am closing this issue for now, feel free to re-open one if you encounter problems. 

Robin
