### ISSUE TITLE
Consult some questions about the paper

### ISSUE THREAD

**Issue by lk-greenbird** [rstrudel/rlbc#4]
I have read your paper "_**Learning to combine primitive skills: A step towards versatile robotic manipulation**_" carefullly, but I don't figure out some points. I want to consult some questions in the form of documents. which is more convenient for me to express the problem clearly. Can you give me your email?

**Comment by rstrudel** [comment]
Sure, my contact infos are on my [webpage](https://www.di.ens.fr/robin.strudel/).
